name: Build

on: [push, pull_request]

jobs:
  cmake:
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [macos-11, macos-12, macos-13, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}.build
      - name: Configure
        run: cmake ${{github.workspace}}/stream_v2/examples -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_LIBZMQ=YES
        working-directory: ${{github.workspace}}.build
      - name: Build
        run: cmake --build .
        working-directory: ${{github.workspace}}.build
